// Generated by CoffeeScript 1.7.1
(function() {
  $(".monogram").click(function() {
    $("body").toggleClass("robeam");
  });

  $(document).ready(function() {
    var audio;
    audio = $(".click")[0];
    $(".logo").mousedown(function() {
      audio.play();
    });
    $(".logo").mouseup(function() {
      audio.play();
    });
  });

}).call(this);
